name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Check format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno check **/*.ts
